version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: cloud
    ports:
      - '6500:5432'
    volumes:
      - postgresDB:/data/postgres
    env_file:
      - ../cloud_ol/.env
volumes:
  postgresDB: